version: '3'

networks:
  nginx-php81-mysql8-mercure:

services:
###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    container_name: mercure
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://mp.lt:5173
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "3000:3000"
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - nginx-php81-mysql8-mercure
###< symfony/mercure-bundle ###
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '8085:8085'
    volumes:
      - ./:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81
      - mysql8
    networks:
      - nginx-php81-mysql8-mercure

  php81:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php81
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/project
    networks:
      - nginx-php81-mysql8-mercure

  mysql8:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE (mysql8 bug)
    networks:
      - nginx-php81-mysql8-mercure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql8
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'secret'
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    networks:
      - nginx-php81-mysql8-mercure

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
